leftnav:
- identifier: 7a7e7b16-9255-d523-4589-27ef46e1c1c5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 32bd1b88-a540-7a4b-e19f-1634fff0f2d8
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: f2623645-2fd5-cec1-8d5b-4c2ca734c032
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 64115dfb-f78f-a0ad-394e-0ecf4a1976e3
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 665dc9c0-29d5-b9f2-2c50-cbc47320457d
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 50
